"use client";

import { useState, useTransition } from "react";
import { generateCounterLines, type CounterLineVariants } from "@/app/actions/counter-lines";
import { FAMILY_LABELS, STAGE_LABELS, type Family, type Stage } from "@/corpus/taxonomy";
import type { WarningRecord, WatchState } from "@/lib/detection/engine";
import { counterLineFor } from "@/lib/counter-lines/lines";
import { clock } from "@/lib/evidence/pack";

export function CounterLineCard({ warning, watch, family, stage }: { warning: WarningRecord | null; watch: WatchState | null; family: Family; stage: Stage | "none" }) {
  const [variants, setVariants] = useState<{ key: string; result: CounterLineVariants } | null>(null);
  const [pending, startTransition] = useTransition();

  if (!warning && watch) {
    const line = counterLineFor(watch.family, watch.stage);
    return (
      <div className="rounded-[14px] border border-warn/50 bg-warn/10 p-4">
        <div className="text-[11px] font-semibold uppercase tracking-[0.16em] text-warn">
          Watching · possible {FAMILY_LABELS[watch.family]} script{watch.stage !== "none" ? ` · ${STAGE_LABELS[watch.stage]}` : ""}
        </div>
        <p className="mt-1.5 text-[13px] leading-snug text-fg/90">
          Genuine calls can open like this. Kavach warns only if the script keeps going. If it does, a calm line to use:
        </p>
        <p className="mt-1.5 text-[15px] font-medium text-fg">“{line.say}”</p>
      </div>
    );
  }

  if (!warning) {
    return (
      <div className="panel flex items-center gap-3 p-4">
        <span className="h-2.5 w-2.5 rounded-full bg-ok" />
        <div>
          <div className="text-sm font-medium text-fg">Listening</div>
          <div className="text-[12.5px] text-muted">No scam script confirmed. A calm line to say will appear here the moment one is.</div>
        </div>
      </div>
    );
  }

  // Follow the live stage once the warning has fired; fall back to the warning's own match.
  const activeFamily = family === "benign" ? warning.family : family;
  const activeStage = family === "benign" ? warning.stage : stage;
  const line = counterLineFor(activeFamily === "benign" ? null : activeFamily, activeStage);
  const key = `${activeFamily}:${activeStage}`;
  const shown = variants?.key === key ? variants.result : null;

  const askForVariants = () => {
    if (activeFamily === "benign" || activeStage === "none") return;
    startTransition(async () => setVariants({ key, result: await generateCounterLines(activeFamily, activeStage) }));
  };

  return (
    <div className="alarm rounded-[14px] border border-danger/60 bg-danger/10 p-5">
      <div className="mb-2 flex flex-wrap items-center gap-2 text-[11px] uppercase tracking-[0.16em] text-danger">
        <span className="font-semibold">Likely scam · {FAMILY_LABELS[warning.family]}</span>
        <span className="tabular font-mono normal-case tracking-normal text-danger/80">warned at {clock(warning.at)}</span>
        {activeStage !== "none" && <span className="normal-case tracking-normal text-fg/70">stage: {STAGE_LABELS[activeStage]}</span>}
      </div>
      <div className="text-[11px] uppercase tracking-[0.14em] text-muted">Say this</div>
      <p className="mt-1 text-2xl font-semibold leading-snug text-fg">“{line.say}”</p>
      <p className="mt-2 text-[13px] text-fg/80">
        <span className="font-semibold text-fg">Then: </span>
        {line.then}
      </p>
      <div className="mt-3 flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={askForVariants}
          disabled={pending || activeStage === "none"}
          className="rounded-md border border-line bg-panel px-3 py-1.5 text-[12px] text-fg hover:border-accent disabled:opacity-50"
        >
          {pending ? "Asking…" : "Other ways to say it"}
        </button>
        {shown?.source === "unavailable" && <span className="text-[12px] text-muted">Alternatives unavailable: {shown.reason}.</span>}
      </div>
      {shown?.source === "llm" && (
        <ul className="mt-3 flex flex-col gap-1.5">
          {shown.lines.map((l) => (
            <li key={l} className="text-[14px] text-fg/90">
              “{l}”
            </li>
          ))}
          <li className="text-[11px] text-faint">Generated by {shown.model} from the family and stage only; the transcript was not sent.</li>
        </ul>
      )}
    </div>
  );
}
